# Generated by Django 2.2.8 on 2022-10-03 22:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '병원/기관',
                'verbose_name_plural': '병원/기관',
            },
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('measurement_time_num', models.IntegerField(blank=True, null=True, verbose_name='측정 회차')),
                ('measurement_time', models.TimeField(blank=True, null=True, verbose_name='측정 회차(시간)')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('NO_RESPONSE', 'NO_RESPONSE'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('oxygen_saturation', models.IntegerField(default=0, verbose_name='산소 포화도 측정 결과')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '산소포화도 측정 결과',
                'verbose_name_plural': '산소포화도 측정 결과',
            },
        ),
        migrations.CreateModel(
            name='MedicationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('medication_time_num', models.IntegerField(blank=True, null=True, verbose_name='복약 회차')),
                ('medication_time', models.TimeField(blank=True, null=True, verbose_name='복약 회차(시간)')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('NO_RESPONSE', 'NO_RESPONSE'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default='PENDING', max_length=20)),
                ('symptom_name', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='이상 종류')),
                ('symptom_severity1', models.TextField(blank=True, max_length=100, null=True, verbose_name='이상 정도1')),
                ('symptom_severity2', models.TextField(blank=True, max_length=100, null=True, verbose_name='이상 정도2')),
                ('symptom_severity3', models.TextField(blank=True, max_length=100, null=True, verbose_name='이상 정도3')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 시간')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '복약 결과',
                'verbose_name_plural': '복약 결과',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('kakao_user_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='전화번호')),
                ('name', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='이름')),
                ('safeout', models.NullBooleanField(default=False, verbose_name='외출 가능 여부')),
                ('additionally_detected_flag', models.NullBooleanField(default=None, verbose_name='추가 균 검출 여부')),
                ('additionally_detected_date', models.DateField(blank=True, null=True, verbose_name='추가 균 검출일')),
                ('treatment_started_date', models.DateField(blank=True, null=True, verbose_name='치료 시작일')),
                ('treatment_end_date', models.DateField(blank=True, null=True, verbose_name='치료 종료일')),
                ('discharged_flag', models.NullBooleanField(default=None, verbose_name='퇴원 여부')),
                ('register_completed_flag', models.BooleanField(default=False, verbose_name='계정 등록 완료 여부')),
                ('medication_manage_flag', models.NullBooleanField(default=None, verbose_name='복약관리 여부')),
                ('daily_medication_count', models.IntegerField(default=0, verbose_name='하루 복약 횟수')),
                ('medication_noti_flag', models.NullBooleanField(default=None, verbose_name='복약알림 여부')),
                ('medication_noti_time_1', models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 1')),
                ('medication_noti_time_2', models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 2')),
                ('medication_noti_time_3', models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 3')),
                ('medication_noti_time_4', models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 4')),
                ('medication_noti_time_5', models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 5')),
                ('visit_manage_flag', models.NullBooleanField(default=None, verbose_name='내원관리 여부')),
                ('next_visiting_date_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='다음 내원일')),
                ('visit_notification_flag', models.NullBooleanField(default=None, verbose_name='내원알림 여부')),
                ('visit_notification_before', models.IntegerField(blank=True, default=None, null=True, verbose_name='내원알림 시간')),
                ('measurement_manage_flag', models.NullBooleanField(default=None, verbose_name='건강관리 여부')),
                ('daily_measurement_count', models.IntegerField(default=0, verbose_name='하루 측정 횟수')),
                ('measurement_noti_flag', models.NullBooleanField(default=None, verbose_name='측정 알림 여부')),
                ('measurement_noti_time_1', models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 1')),
                ('measurement_noti_time_2', models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 2')),
                ('measurement_noti_time_3', models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 3')),
                ('measurement_noti_time_4', models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 4')),
                ('measurement_noti_time_5', models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.Hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자',
            },
        ),
        migrations.CreateModel(
            name='Sputum_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_res', models.CharField(choices=[('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4'), ('-', '-')], max_length=20)),
                ('positive_negative', models.CharField(choices=[('결핵균 양성', '결핵균 양성'), ('결핵균 음성', '결핵균 음성'), ('검사중', '검사중')], max_length=40)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('patient_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.Hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('anonymous', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count_of_commnet', models.IntegerField(blank=True, null=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pcr_Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_res', models.CharField(choices=[('양성', '양성'), ('음성', '음성')], max_length=20)),
                ('patient_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_message_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('noti_time_num', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENDING', 'SENDING'), ('RETRY', 'RETRY'), ('RESERVED', 'RESERVED'), ('DELIVERED', 'DELIVERED'), ('SUSPENDED', 'SUSPENDED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=20)),
                ('recipient_number', models.CharField(max_length=50, verbose_name='수신인 번호')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('tries_left', models.IntegerField(default=3)),
                ('send_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_result', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='core.MeasurementResult')),
                ('medication_result', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='core.MedicationResult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_records', to='core.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicationresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_results', to='core.Patient'),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_results', to='core.Patient'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('kakao_user_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('patient_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
            options={
                'verbose_name': '보호자',
                'verbose_name_plural': '보호자',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at_comment', models.DateField(auto_created=django.utils.timezone.now)),
                ('comment', models.TextField(max_length=200)),
                ('created_at_comment', models.DateField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Post')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
