# Generated by Django 2.2.8 on 2022-10-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sputum_inspection',
            name='patient_set',
        ),
        migrations.DeleteModel(
            name='Pcr_Inspection',
        ),
        migrations.DeleteModel(
            name='Sputum_Inspection',
        ),
    ]
