# Generated by Django 2.2.8 on 2022-10-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pcr_inspection_sputum_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr_inspection',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
