# Generated by Django 2.2.8 on 2022-10-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pcr_inspection_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcr_inspection',
            options={'verbose_name': 'PCR 검사', 'verbose_name_plural': 'PCR 검사'},
        ),
        migrations.AlterModelOptions(
            name='sputum_inspection',
            options={'verbose_name': '객담 도말 검사', 'verbose_name_plural': '객담 도말 검사'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='additionally_detected_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='additionally_detected_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='daily_measurement_count',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharged_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_manage_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_4',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_5',
        ),
    ]
