# Generated by Django 2.2.6 on 2019-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
