# Generated by Django 2.2.8 on 2022-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221004_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='vision',
            field=models.FloatField(blank=True, null=True, verbose_name='시력'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='몸무게'),
        ),
    ]
