# Generated by Django 2.2.6 on 2019-10-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_change_patient_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
