# Generated by Django 2.2.8 on 2022-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221007_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='vision',
        ),
        migrations.AddField(
            model_name='patient',
            name='vision_left',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='왼쪽 시력'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vision_right',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name=' 오른쪽 시력'),
        ),
    ]
