# Generated by Django 2.2.8 on 2022-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221020_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='비밀번호'),
        ),
    ]
