# Generated by Django 2.2.6 on 2019-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patient_kakao_user_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='additionally_detected_date',
            field=models.DateField(null=True, verbose_name='추가 균 검출일'),
        ),
        migrations.AddField(
            model_name='patient',
            name='additionally_detected_flag',
            field=models.NullBooleanField(default=None, verbose_name='추가 균 검출 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='daily_measurement_count',
            field=models.IntegerField(default=0, verbose_name='하루 측정 횟수'),
        ),
        migrations.AddField(
            model_name='patient',
            name='daily_medication_count',
            field=models.IntegerField(default=0, verbose_name='하루 복약 횟수'),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharged_flag',
            field=models.NullBooleanField(default=None, verbose_name='퇴원 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_manage_flag',
            field=models.NullBooleanField(default=None, verbose_name='건강관리 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='measurement_noti_flag',
            field=models.NullBooleanField(default=None, verbose_name='측정 알림 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='measurement_noti_time_1',
            field=models.TimeField(default=None, null=True, verbose_name='측정 알림 시간 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='measurement_noti_time_2',
            field=models.TimeField(default=None, null=True, verbose_name='측정 알림 시간 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='measurement_noti_time_3',
            field=models.TimeField(default=None, null=True, verbose_name='측정 알림 시간 3'),
        ),
        migrations.AddField(
            model_name='patient',
            name='measurement_noti_time_4',
            field=models.TimeField(default=None, null=True, verbose_name='측정 알림 시간 4'),
        ),
        migrations.AddField(
            model_name='patient',
            name='measurement_noti_time_5',
            field=models.TimeField(default=None, null=True, verbose_name='측정 알림 시간 5'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_manage_flag',
            field=models.NullBooleanField(default=None, verbose_name='복약관리 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_noti_flag',
            field=models.NullBooleanField(default=None, verbose_name='복약알림 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_noti_time_1',
            field=models.TimeField(default=None, null=True, verbose_name='복약알림 시간 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_noti_time_2',
            field=models.TimeField(default=None, null=True, verbose_name='복약알림 시간 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_noti_time_3',
            field=models.TimeField(default=None, null=True, verbose_name='복약알림 시간 3'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_noti_time_4',
            field=models.TimeField(default=None, null=True, verbose_name='복약알림 시간 4'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_noti_time_5',
            field=models.TimeField(default=None, null=True, verbose_name='복약알림 시간 5'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_visiting_date',
            field=models.DateField(default=None, null=True, verbose_name='다음 내원일'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_flag',
            field=models.NullBooleanField(default=None, verbose_name='계정 등록 완료 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_started_date',
            field=models.DateField(null=True, verbose_name='치료 시작일'),
        ),
        migrations.AddField(
            model_name='patient',
            name='visit_manage_flag',
            field=models.NullBooleanField(default=None, verbose_name='내원관리 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='visit_notification_flag',
            field=models.NullBooleanField(default=None, verbose_name='내원알림 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='visit_notification_time',
            field=models.TimeField(default=None, null=True, verbose_name='내원알림 시간'),
        ),
    ]
