# Generated by Django 2.2.6 on 2019-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_alter_patient_next_visiting_date_to_next_visiting_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='visit_notification_time',

        ),
        migrations.AddField(
            model_name='patient',
            name='visit_notification_before',
            field=models.IntegerField(default=None, null=True, verbose_name='내원알림 시간'),
        ),
    ]
