# Generated by Django 2.2.8 on 2022-11-27 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221122_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vision_left',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2.5), django.core.validators.MaxValueValidator(0.0)], verbose_name='왼쪽 시력'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vision_right',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2.5), django.core.validators.MaxValueValidator(0.0)], verbose_name=' 오른쪽 시력'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(150.0), django.core.validators.MaxValueValidator(0.0)], verbose_name='몸무게'),
        ),
    ]
