# Generated by Django 2.2.6 on 2019-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_patient_visit_notification_time_to_visit_notification_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatment_end_date',
            field=models.DateField(null=True, verbose_name='치료 시작일'),
        ),
    ]
