# Generated by Django 2.2.6 on 2019-11-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_medication_result_and_measurement_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': '병원/기관', 'verbose_name_plural': '병원/기관'},
        ),
    ]
