# Generated by Django 2.2.6 on 2019-10-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patient_treatment_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('date', models.DateTimeField(verbose_name='날짜')),
                ('measurement_result', models.IntegerField(verbose_name='측정 결과')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('date', models.DateField(verbose_name='날짜')),
                ('medication_result_1', models.IntegerField(default=0, verbose_name='복용 결과 1')),
                ('medication_result_2', models.IntegerField(default=0, verbose_name='복용 결과 2')),
                ('medication_result_3', models.IntegerField(default=0, verbose_name='복용 결과 3')),
                ('medication_result_4', models.IntegerField(default=0, verbose_name='복용 결과 4')),
                ('medication_result_5', models.IntegerField(default=0, verbose_name='복용 결과 5')),
            ],
        ),
    ]
