# Generated by Django 2.2.8 on 2022-12-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221127_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_4',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_5',
        ),
        migrations.AddField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
