# Generated by Django 2.2.6 on 2019-10-30 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_measurementresult_medicationresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementresult',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medicationresult',
            name='code',
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_patient', to='core.Patient'),
        ),
        migrations.AddField(
            model_name='medicationresult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_patient', to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_1',
            field=models.CharField(choices=[('PA', 'padding'), ('SC', 'success'), ('DC', 'delay_success'), ('NR', 'no_response'), ('FA', 'fail'), ('SE', 'side_effect')], default='PA', max_length=2, verbose_name='복용 결과 1'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_2',
            field=models.CharField(choices=[('PA', 'padding'), ('SC', 'success'), ('DC', 'delay_success'), ('NR', 'no_response'), ('FA', 'fail'), ('SE', 'side_effect')], default='PA', max_length=2, verbose_name='복용 결과 2'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_3',
            field=models.CharField(choices=[('PA', 'padding'), ('SC', 'success'), ('DC', 'delay_success'), ('NR', 'no_response'), ('FA', 'fail'), ('SE', 'side_effect')], default='PA', max_length=2, verbose_name='복용 결과 3'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_4',
            field=models.CharField(choices=[('PA', 'padding'), ('SC', 'success'), ('DC', 'delay_success'), ('NR', 'no_response'), ('FA', 'fail'), ('SE', 'side_effect')], default='PA', max_length=2, verbose_name='복용 결과 4'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_5',
            field=models.CharField(choices=[('PA', 'padding'), ('SC', 'success'), ('DC', 'delay_success'), ('NR', 'no_response'), ('FA', 'fail'), ('SE', 'side_effect')], default='PA', max_length=2, verbose_name='복용 결과 5'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_end_date',
            field=models.DateField(null=True, verbose_name='치료 종료일'),
        ),
    ]
