# Generated by Django 2.2.8 on 2022-12-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221208_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='daily_measurement_count',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_manage_flag',
        ),
    ]
