# Generated by Django 2.2.6 on 2019-11-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_change_meta_options_on_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
