# Generated by Django 2.2.6 on 2019-10-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191030_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementresult',
            old_name='date',
            new_name='datetime',
        ),
    ]
