# Generated by Django 2.2.8 on 2022-12-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20221209_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='daily_measurement_count',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_manage_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_flag',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_4',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='measurement_noti_time_5',
        ),
    ]
