# Generated by Django 2.2.6 on 2019-11-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_change_patient_registered_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='health_manage_flag',
            new_name='measurement_manage_flag',
        ),
    ]
