# Generated by Django 2.2.8 on 2023-01-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20221210_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputum_inspection',
            name='inspection_res',
            field=models.CharField(choices=[('-', '-'), ('+', '+'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4')], max_length=20),
        ),
    ]
