# Generated by Django 2.2.6 on 2019-11-11 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_rename_health_manage_flag_to_measurement_manage_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_1',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('DELAYED_SUCCESS', 'delay_success'), ('NO_RESPONSE', 'no_response'), ('FAILED', 'fail'), ('SIDE_EFFECT', 'side_effect')], default='PENDING', max_length=15, verbose_name='1회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_2',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('DELAYED_SUCCESS', 'delay_success'), ('NO_RESPONSE', 'no_response'), ('FAILED', 'fail'), ('SIDE_EFFECT', 'side_effect')], default='PENDING', max_length=15, verbose_name='2회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_3',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('DELAYED_SUCCESS', 'delay_success'), ('NO_RESPONSE', 'no_response'), ('FAILED', 'fail'), ('SIDE_EFFECT', 'side_effect')], default='PENDING', max_length=15, verbose_name='3회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_4',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('DELAYED_SUCCESS', 'delay_success'), ('NO_RESPONSE', 'no_response'), ('FAILED', 'fail'), ('SIDE_EFFECT', 'side_effect')], default='PENDING', max_length=15, verbose_name='4회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_5',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('DELAYED_SUCCESS', 'delay_success'), ('NO_RESPONSE', 'no_response'), ('FAILED', 'fail'), ('SIDE_EFFECT', 'side_effect')], default='PENDING', max_length=15, verbose_name='5회차 복용 결과'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(default='default', max_length=10)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='core.Hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
