# Generated by Django 2.2.8 on 2023-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230124_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputum_inspection',
            name='positive_negative',
            field=models.CharField(choices=[('결핵균 양성', '결핵균 양성'), ('미약', '미약'), ('결핵균 음성', '결핵균 음성'), ('검사중', '검사중')], max_length=40),
        ),
    ]
