# Generated by Django 2.2.6 on 2019-11-14 20:51

import core.models.models
import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191114_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_1',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('NO_RESPONSE', 'NO_RESPONSE'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.models.MedicationResult.Result('PENDING'), max_length=2, verbose_name='1회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_2',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('NO_RESPONSE', 'NO_RESPONSE'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.models.MedicationResult.Result('PENDING'), max_length=2, verbose_name='2회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_3',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('NO_RESPONSE', 'NO_RESPONSE'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.models.MedicationResult.Result('PENDING'), max_length=2, verbose_name='3회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_4',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('NO_RESPONSE', 'NO_RESPONSE'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.models.MedicationResult.Result('PENDING'), max_length=2, verbose_name='4회차 복용 결과'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_result_5',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('NO_RESPONSE', 'NO_RESPONSE'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.models.MedicationResult.Result('PENDING'), max_length=2, verbose_name='5회차 복용 결과'),
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('SUSPENDED', 'SUSPENDED'), ('SENDING', 'SENDING'), ('DELIVERED', 'DELIVERED'), ('CANCELED', 'CANCELED')], default=core.models.models.NotificationRecord.Status('PENDING'), max_length=15)),
                ('recipient_number', models.CharField(max_length=50, verbose_name='수신인 번호')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tries_left', models.IntegerField(default=3)),
                ('reserved_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 5, 51, 28, 7113))),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_records', to='core.Patient')),
            ],
        ),
    ]
