# Generated by Django 2.2.6 on 2019-11-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_field_medication_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecord',
            name='status_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
