# Generated by Django 2.2.8 on 2023-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='print_created_at',
            field=models.CharField(default='', max_length=10),
        ),
    ]
