# Generated by Django 2.2.8 on 2023-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comment_print_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='print_created_at',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='print_created_at',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
