# Generated by Django 2.2.6 on 2019-11-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_field_status_updated_at_on_notificationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='notified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
