# Generated by Django 2.2.6 on 2019-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_field_notified_at_on_medicationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationresult',
            name='status_info',
            field=models.TextField(default=''),
        ),
    ]
