# Generated by Django 2.2.8 on 2023-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230130_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr_inspection',
            name='pcr_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='sputum_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
