# Generated by Django 2.2.8 on 2023-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230130_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr_inspection',
            name='th',
            field=models.IntegerField(default=1, verbose_name='번째 검사'),
        ),
        migrations.AddField(
            model_name='sputum_inspection',
            name='method',
            field=models.CharField(choices=[('객담 검체', '객담 검체'), ('기관지경 검체', '기관지경 검체'), ('other', 'other')], default='', max_length=20, verbose_name='검사 방법'),
        ),
        migrations.AddField(
            model_name='sputum_inspection',
            name='th',
            field=models.IntegerField(default=1, verbose_name='번째 검사'),
        ),
        migrations.AlterField(
            model_name='pcr_inspection',
            name='date',
            field=models.DateField(null=True, verbose_name='검사 날짜'),
        ),
        migrations.AlterField(
            model_name='pcr_inspection',
            name='inspection_res',
            field=models.CharField(choices=[('양성', '양성'), ('음성', '음성')], max_length=20, verbose_name='양성/음성'),
        ),
        migrations.AlterField(
            model_name='pcr_inspection',
            name='pcr_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='검사 날짜_출력용'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='date',
            field=models.DateField(null=True, verbose_name='검사 날짜'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='inspection_res',
            field=models.CharField(choices=[('-', '-'), ('+/-', '+/-'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4')], max_length=20, verbose_name='정도'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='positive_negative',
            field=models.CharField(choices=[('결핵균 양성', '결핵균 양성'), ('결핵균 음성', '결핵균 음성'), ('검사중', '검사중')], max_length=40, verbose_name='양성/음성'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='sputum_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='검사 날짜_출력용'),
        ),
    ]
