# Generated by Django 2.2.8 on 2023-01-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230130_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcr_inspection',
            name='th',
        ),
    ]
