# Generated by Django 2.2.6 on 2019-11-17 18:37

import core.models.notification_record
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_severity_and_alter_status_info_medicationresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationrecord',
            old_name='reserved_at',
            new_name='send_at',
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='medication_time',
            field=models.IntegerField(null=True, verbose_name='복약 회차'),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='notified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='biz_message_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='measurement_record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='core.MeasurementResult'),
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='medication_record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='core.MedicationResult'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.RenameField(
            model_name='medicationresult',
            old_name='medication_time',
            new_name='medication_time_num'
        ),
        migrations.AddField(
            model_name='medicationresult',
            name='medication_time',
            field=models.TimeField(verbose_name='복약 회차(시간)', null=True),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SENDING', 'SENDING'), ('RESERVERD', 'RESERVED'), ('DELIVERED', 'DELIVERED'), ('SUSPENDED', 'SUSPENDED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default=core.models.NotificationRecord.STATUS('PENDING'), max_length=15),
        ),
    ]
