# Generated by Django 2.2.8 on 2023-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_pcr_inspection_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr_inspection',
            name='pcr_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='검사 날짜_출력용(입력 x)'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='sputum_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='검사 날짜_출력용(입력 x)'),
        ),
    ]
