# Generated by Django 2.2.6 on 2019-11-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementresult',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='medication_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='복약 회차'),
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_time',
            field=models.TimeField(blank=True, null=True, verbose_name='복약 회차(시간)'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='medication_time_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='복약 회차'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_results', to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='severity',
            field=models.IntegerField(blank=True, null=True, verbose_name='이상 정도'),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='biz_message_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='measurement_record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='core.MeasurementResult'),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='medication_record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='core.MedicationResult'),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='additionally_detected_date',
            field=models.DateField(blank=True, null=True, verbose_name='추가 균 검출일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='measurement_noti_time_1',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='measurement_noti_time_2',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='measurement_noti_time_3',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 3'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='measurement_noti_time_4',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='measurement_noti_time_5',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='측정 알림 시간 5'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_noti_time_1',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_noti_time_2',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_noti_time_3',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 3'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_noti_time_4',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_noti_time_5',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간 5'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visiting_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='다음 내원일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='치료 종료일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_started_date',
            field=models.DateField(blank=True, null=True, verbose_name='치료 시작일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_notification_before',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='내원알림 시간'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.Hospital'),
        ),
    ]
