# Generated by Django 2.2.8 on 2023-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20230223_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='sputum_inspection',
            name='smear_culture',
            field=models.CharField(choices=[('도말', '도말'), ('배양', '배양')], default='', max_length=20, verbose_name='도말/배양'),
        ),
    ]
