# Generated by Django 2.2.6 on 2019-11-19 18:46

import core.models.medication_result
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('NO_RESPONSE', 'NO_RESPONSE'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.medication_result.MedicationResult.STATUS('PENDING'), max_length=15),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='status_info',
            field=models.TextField(default='', max_length=100, verbose_name='이상 종류'),
        ),
    ]
