# Generated by Django 2.2.6 on 2019-11-19 18:51

import core.models.medication_result
import core.models.notification_record
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_field_status_and_status_info_on_medicationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('NO_RESPONSE', 'NO_RESPONSE'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('FAILED', 'FAILED'), ('SIDE_EFFECT', 'SIDE_EFFECT')], default=core.models.medication_result.MedicationResult.STATUS('PENDING'), max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SENDING', 'SENDING'), ('RESERVERD', 'RESERVED'), ('DELIVERED', 'DELIVERED'), ('SUSPENDED', 'SUSPENDED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default=core.models.notification_record.NotificationRecord.STATUS('PENDING'), max_length=20),
        ),
    ]
