# Generated by Django 2.2.8 on 2023-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sputum_inspection_smear_culture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sputum_inspection',
            options={'verbose_name': '도말, 배양 검사', 'verbose_name_plural': '도말, 배양 검사'},
        ),
        migrations.RenameField(
            model_name='pcr_inspection',
            old_name='date',
            new_name='insp_date',
        ),
        migrations.RenameField(
            model_name='sputum_inspection',
            old_name='date',
            new_name='insp_date',
        ),
        migrations.RemoveField(
            model_name='pcr_inspection',
            name='inspection_res',
        ),
        migrations.RemoveField(
            model_name='pcr_inspection',
            name='pcr_date',
        ),
        migrations.RemoveField(
            model_name='sputum_inspection',
            name='inspection_res',
        ),
        migrations.RemoveField(
            model_name='sputum_inspection',
            name='positive_negative',
        ),
        migrations.RemoveField(
            model_name='sputum_inspection',
            name='smear_culture',
        ),
        migrations.RemoveField(
            model_name='sputum_inspection',
            name='sputum_date',
        ),
        migrations.AddField(
            model_name='pcr_inspection',
            name='pcr_result',
            field=models.CharField(choices=[('양성', '양성'), ('음성', '음성')], default='', max_length=20, verbose_name='검사 결과'),
        ),
        migrations.AddField(
            model_name='sputum_inspection',
            name='culture_result',
            field=models.CharField(choices=[('양성', '양성'), ('음성', '음성'), ('검사중', '검사중'), ('오염', '오염'), ('미시행', '미시행')], default='미시행', max_length=20, verbose_name='배양검사 결과'),
        ),
        migrations.AddField(
            model_name='sputum_inspection',
            name='smear_result',
            field=models.CharField(choices=[('-', '-'), ('+-', '+-'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+'), ('미시행', '미시행')], default='미시행', max_length=20, verbose_name='도말검사 결과'),
        ),
        migrations.AlterField(
            model_name='pcr_inspection',
            name='method',
            field=models.CharField(choices=[('객담', '객담'), ('기관지내시경 검체', '기관지내시경 검체'), ('기타', '기타')], default='', max_length=20, verbose_name='검사 방법'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='method',
            field=models.CharField(choices=[('객담', '객담'), ('기관지내시경 검체', '기관지내시경 검체'), ('기타', '기타')], default='', max_length=20, verbose_name='검체 종류'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='th',
            field=models.CharField(choices=[('1차', '1차'), ('2차', '2차'), ('3차', '3차')], default='1차', max_length=20, verbose_name='검체 세부 분류'),
        ),
    ]
