# Generated by Django 2.2.6 on 2019-11-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_status_enum_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
    ]
