# Generated by Django 2.2.8 on 2023-03-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20230301_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputum_inspection',
            name='culture_result',
            field=models.CharField(choices=[('검사중', '검사중'), ('양성', '양성'), ('음성', '음성'), ('검사중', '검사중'), ('오염', '오염'), ('미시행', '미시행')], default='미시행', max_length=20, verbose_name='배양검사 결과'),
        ),
        migrations.AlterField(
            model_name='sputum_inspection',
            name='smear_result',
            field=models.CharField(choices=[('검사중', '검사중'), ('-', '-'), ('+-', '+-'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+'), ('미시행', '미시행')], default='미시행', max_length=20, verbose_name='도말검사 결과'),
        ),
    ]
