# Generated by Django 2.2.6 on 2019-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_field_date_on_medicationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='status_info',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='이상 종류'),
        ),
    ]
