# Generated by Django 2.2.8 on 2023-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20230304_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='display_dashboard',
            field=models.BooleanField(default=True, verbose_name='대쉬보드에서 보이기'),
        ),
    ]
