# Generated by Django 2.2.6 on 2019-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_field_status_info_null_true'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='measurementresult',
            name='checked_at',
        ),
        migrations.RenameField(
            model_name='measurementresult',
            old_name='medication_time',
            new_name='measurement_time_num'
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='measurement_time_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='측정 회차'),
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='measured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='확인 시간'),
        ),
    ]

