# Generated by Django 2.2.6 on 2019-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_measurement_time_num_on_measurementresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationresult',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='확인 시간'),
        ),
        migrations.AlterField(
            model_name='medicationresult',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 시간'),
        ),
    ]
