# Generated by Django 2.2.8 on 2023-08-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_patient_display_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성별'),
        ),
    ]
