# Generated by Django 2.2.8 on 2023-08-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230813_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='치료 종료 일자'),
        ),
    ]
