# Generated by Django 2.2.8 on 2023-08-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230813_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='성별'),
        ),
    ]
