# Generated by Django 2.2.6 on 2019-11-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_status_default_with_enum_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementresult',
            options={'verbose_name': '산소포화도 측정 결과', 'verbose_name_plural': '산소포화도 측정 결과'},
        ),
        migrations.AlterModelOptions(
            name='medicationresult',
            options={'verbose_name': '복약 결과', 'verbose_name_plural': '복약 결과'},
        ),
    ]
