# Generated by Django 2.2.8 on 2023-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230830_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='sputum_inspection',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_end_date',
            field=models.DateField(null=True, verbose_name='치료 종료일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_started_date',
            field=models.DateField(null=True, verbose_name='치료 시작일'),
        ),
    ]
