# Generated by Django 2.2.6 on 2019-11-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_change_meta_options_on_measurementresult_medicationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='kakao_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
