# Generated by Django 2.2.8 on 2023-12-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_patient_remind_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'verbose_name': '환자', 'verbose_name_plural': '환자'},
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.TextField()),
                ('intensity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_effects', to='core.MedicationResult')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.DateTimeField()),
                ('daily_num', models.IntegerField(default=1, verbose_name='복약 번호')),
                ('activate', models.BooleanField(default=True, verbose_name='알림 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_type', models.CharField(choices=[('MEDICATION_NOTI', 'MEDICATION_NOTI'), ('VISIT_NOTI', 'VISIT_NOTI')], default='MEDICATION_NOTI', max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_time_tables', to='core.Patient')),
            ],
            options={
                'verbose_name': '복약 알림 시간',
                'verbose_name_plural': '복약 알림 시간',
            },
        ),
    ]
