# Generated by Django 2.2.8 on 2023-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_notificationtimetable_sideeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtimetable',
            name='daily_num',
            field=models.IntegerField(default=0, verbose_name='복약 번호'),
        ),
    ]
