# Generated by Django 2.2.6 on 2019-11-24 17:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_user_on_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationrecord',
            old_name='measurement_record',
            new_name='measurement_result',
        ),
        migrations.RenameField(
            model_name='notificationrecord',
            old_name='medication_record',
            new_name='medication_result',
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='measurement_time',
            field=models.TimeField(blank=True, null=True, verbose_name='측정 회차(시간)'),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('NO_RESPONSE', 'NO_RESPONSE'), ('SUCCESS', 'SUCCESS'), ('DELAYED_SUCCESS', 'DELAYED_SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
