# Generated by Django 2.2.8 on 2023-12-01 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_notificationtimetable_daily_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.TimeField(blank=True, default=None, null=True, verbose_name='복약알림 시간')),
                ('daily_num', models.IntegerField(default=1, verbose_name='복약 번호')),
                ('activate', models.BooleanField(default=True, verbose_name='알림 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_type', models.CharField(choices=[('MEDICATION_NOTI', 'MEDICATION_NOTI'), ('VISIT_NOTI', 'VISIT_NOTI')], default='MEDICATION_NOTI', max_length=20)),
            ],
            options={
                'verbose_name': '복약 알림 시간',
                'verbose_name_plural': '복약 알림 시간',
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'verbose_name': '환자', 'verbose_name_plural': '환자'},
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='NotificationTimeTable',
        ),
        migrations.AddField(
            model_name='notificationtime',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_time_tables', to='core.Patient'),
        ),
    ]
