# Generated by Django 2.2.8 on 2023-12-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20231201_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtime',
            name='notification_time',
            field=models.DateTimeField(),
        ),
    ]
